//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReGen.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings_Designer : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings_Designer defaultInstance = ((Settings_Designer)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings_Designer())));
        
        public static Settings_Designer Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("33-51-17")]
        public string CMM {
            get {
                return ((string)(this["CMM"]));
            }
            set {
                this["CMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public ulong TestNumber {
            get {
                return ((ulong)(this["TestNumber"]));
            }
            set {
                this["TestNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TechnicianName {
            get {
                return ((string)(this["TechnicianName"]));
            }
            set {
                this["TechnicianName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int TechnicianStamp {
            get {
                return ((int)(this["TechnicianStamp"]));
            }
            set {
                this["TechnicianStamp"] = value;
            }
        }
    }
}
